name: Build binaries

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  bulid:
    name: Build and release binaries
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Build
      run: sudo ./build_binaries.sh
